# apacing matters in yml file
# select a version to perform your operations
version: '3'

# services is nothing but a container
services:
  api:
    build:  .
    depends_on:
      - postgres
    ports:
      - 8000:8000
      # <port on localhost: port on container>
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    env_file:
      - ./.env

    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres 

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:


# > docker-compose up --help
# > docker-compose up -d
#  -d, --detach    Detached mode: Run containers in the
#                  background
# > docker ps -a
# > docker ps
# > docker-compose down
# > docker ls

